server:
  port: 8080
  tomcat:
    uri-encoding: utf-8
    basedir: /tmp/tomcat

spring:
  profiles:
    active: dev

  thymeleaf:
    cache: false

  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

  aop:
    proxy-target-class: true

  servlet:
    multipart:
      enabled: true
      # 单个文件的最大上限
      max-file-size: 10MB
      # 单个请求的文件总大小上限
      max-request-size: 30MB

#  boot:
#    admin:
#      client:
#        url: http://localhost:8081


management:
  endpoints:
    web:
      exposure:
        include: /*

mybatis-plus:
  # 实体类扫描路径
  type-aliases-package: com.mx.ai.sports.monitor.entity,com.mx.ai.sports.system.entity
  # xml 扫描路径
  mapper-locations: classpath:mapper/*/*.xml
  configuration:
    jdbc-type-for-null: null
  global-config:
    # 关闭 mybatis-plus的 banner
    banner: false

sms:
  regionId: cn-hangzhou
  accessKeyId: LTAI4FqD1WE7i5mPYsQ7UMrJ
  accessKeySecret: 6sKjUKKQ8tNp12qDukJZuCpjcpU87P
  signName: 考吧
  templateCode: SMS_177247817

jpush:
  masterSecret: c53cc7015e8c636593e71805
  appKey: 7c79ff0be8a56c37e88591ee
  title: 考吧
  largeIcon: http://www.jiguang.cn/largeIcon.jpg


#在使用@ApiModelProperty注解在字段上时，如果字段的类型为Long或是int类型，那么程序启动后，访问swagger-ui.html的页面，程序会报错:
#java.lang.NumberFormatException: For input string: ""
#调整日志的级别来忽略异常
logging:
  level:
    io.swagger.models.parameters.AbstractSerializableParameter: error
